#Get all User

GET  http://localhost:9494/api/v1/categories HTTP/1.1

###

#Post a new user
POST http://localhost:9494/api/v1/categories HTTP/1.1
content-type: application/json


{
    "name": "iPhone 17",
    "description": "Với dung lượng lên tới 1TB bộ mã màu sinh động"
}

###
DELETE   http://localhost:9494/api/v1/categories/6534d9daab94b6583114c9ac HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTM0ZDhjNWFiOTRiNjU4MzExNGM5YTIiLCJlbWFpbCI6InF1eUBnbWFpbC5jb20iLCJpYXQiOjE2OTc5NjI0MDgsImV4cCI6MTY5OTI1ODQwOH0.d263IOj74lB-Vz0CFAOHCjDQyCByITLBDxRo_M-o9Ic

###
PATCH  http://localhost:9494/api/v1/categories/2 HTTP/1.1
content-type: application/json

{
    "description": "dây điện: 3.7m,Công suất hút: 12000 Pa"
}