#Get all User
POST http://localhost:8080/api/v1/auth/login HTTP/1.1
content-type: application/json

{
 
  "email": "tronghoangg@gmail.com",
  "password": "Tronghoang123"
  
}
### User Trong

#Post a new user
POST   http://localhost:8080/api/v1/categories HTTP/1.1
content-type: application/json

{
  "name": "Thiết Bị Cho Sức Khỏe",
  "description": "Thiết Bị Cho Sức Khỏe và các phụ kiện kèm theo giá tốt.",
  "products": []
}


###
PATCH    http://localhost:8080/api/v1/categories/65688e42c94df3a50a2a8e45 HTTP/1.1
content-type: application/json

{
  "name": "Điện thoại"
}
###
PATCH  http://localhost:9494/api/v1/categories/2 HTTP/1.1
content-type: application/json

{
    "description": "dây điện: 3.7m,Công suất hút: 12000 Pa"
}