  #Get all User
POST http://localhost:8080/api/v1/auth/login HTTP/1.1
content-type: application/json

{
 
  "email": "tronghoangg@gmail.com",
  "password": "Tronghoang123"
  
}
### User Trong

###
POST   http://localhost:3000/api/v1/categories HTTP/1.1
content-type: application/json

{
  "id": "5",
  "name": "mới1",
  "images": "https://cdn.tgdd.vn/Products/Images/42/305658/Slider/vi-vn-iphone-15-pro-max-4-1020x570.jpg"
}


###
PATCH    http://localhost:8080/api/v1/categories/65688e42c94df3a50a2a8e45 HTTP/1.1
content-type: application/json

{
  "name": "Điện thoại"
}
###
DELETE   http://localhost:3000/api/v1/categories/65904d4d4c1249aefe9e91a4 HTTP/1.1
