#Post a new user
POST http://localhost:8080/api/v1/customers HTTP/1.1
content-type: application/json

{
  "firstName": "Hoang Xuan",
  "lastName": "test",
  "email": "test@gmail.com",
  "phoneNumber": "0123456556",
  "address": "Đà Nẵng",
  "birthDay": "1994-09-10",
  "password": "Eqwert123"
}