#Get all User

POST http://localhost:9494/api/v1/auth/login HTTP/1.1
content-type: application/json

{
 
  "email": "ngocanh30927@gmail.com",
  "password": "Ngocanh123"
  
}
###
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTY4NGY0ZWJiY2IyZjkwMzY2OTBiYmYiLCJlbWFpbCI6InRyb25naG9hbmdnQGdtYWlsLmNvbSIsImlhdCI6MTcwMTM0ODU2MSwiZXhwIjoxNzAyNjQ0NTYxfQ.SqzmKQWa982S6TawYkqRWhVZepxdj0yUevABjO0jlIc
 
#Post a new user
POST http://localhost:9494/api/v1/employees HTTP/1.1
content-type: application/json

{
  "firstName": "Smith",
  "lastName": "Rowe",
  "email": "rowe@gmail.com",
  "phoneNumber": "0123457766",
  "address": "Đà Nẵng",
  "birthDay": "1995-09-10",
  "password": "Ngocanh123",
  "photo": "/images/avatar-default.jpg",
  "role": "Admin",
  "position": "Manger Associate",
  "department": "Manger",
  "isActive": true
}

###
DELETE   http://localhost:8080/api/v1/employees/65647b83955a14cdf71347b1 HTTP/1.1/65647bb1955a14cdf71347b3 HTTP/1.1


###
PATCH  http://localhost:9494/api/v1/employees/652571e6d0214e6b58ff4266 HTTP/1.1
content-type: application/json

{
    "PhoneNumber": "0986712124"
}