#Get all User


###
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTM0ZDhjNWFiOTRiNjU4MzExNGM5YTIiLCJlbWFpbCI6InF1eUBnbWFpbC5jb20iLCJpYXQiOjE2OTc5NjI0MDgsImV4cCI6MTY5OTI1ODQwOH0.d263IOj74lB-Vz0CFAOHCjDQyCByITLBDxRo_M-o9Ic
 
#Post a new user
POST http://localhost:8080/api/v1/employees HTTP/1.1
content-type: application/json

{
  "firstName": "Van",
  "lastName": "Hieu",
  "email": "vanquyhieu@gmail.com",
  "phoneNumber": "0123456555",
  "address": "Đà Nẵng",
  "birthDay": "1995-09-10",
  "password": "Vanhieu123",
  "photo": " "
}

###
DELETE   http://localhost:9494/api/v1/auth/login HTTP/1.1/652fc8422feb808e0ea84bde HTTP/1.1


###
PATCH  http://localhost:9494/api/v1/employees/652571e6d0214e6b58ff4266 HTTP/1.1
content-type: application/json

{
    "PhoneNumber": "0986712124"
}