#Get all User

GET  http://localhost:9494/api/v1/products HTTP/1.1

###

#Post a new user
POST http://localhost:8080/api/v1/products HTTP/1.1
content-type: application/json

{
  "name": "Laptop HP Pavilion 15 eg2034TX i7 1255U/8GB/512GB/2GB MX550/Win11 (6K780PA)",
  "slug": "", 
  "supplier": "656a0f5200d2b32aa0693b85", 
  "category": "65688ef0c94df3a50a2a8e49", 
  "price": 50, 
  "meteTitle": "Laptop HP Pavilion 15 eg2034TX i7 1255U/8GB/512GB/2GB MX550/Win11 (6K780PA)", 
  "meteDescription": "Laptop HP Pavilion 15 eg2034TX i7 (6K780PA) hứa hẹn sẽ là một đối thủ đáng quan ngại trong phân khúc laptop học tập - văn phòng khi sở hữu cấu hình mạnh mẽ đến từ chip Intel Gen 12 cùng ngoại hình đơn giản nhưng không kém phần hiện đại.", 
  "content": "Nội dung sản phẩm", 
  "rating": 4, 
  "reviews": [
    {
      "rating": 5,
      "comment": "Bình luận 1",
      "customerId": "656db1879b6e79d96e994777"
    },
    {
      "rating": 4,
      "comment": "Bình luận 2",
      "customerId": "656db3759171a0d052185716"
    }
  ],
  "thumbnail": "hp-pavilion-15-eg2034tx-i7-6k780pa-ab.jpg",
  "images": [
    {
      "url": "hp-pavilion-15-eg2034tx-i7-6k780pa-ab.jpg",
      "alt": "Mô tả hình ảnh 1",
      "caption": "Chú thích hình ảnh 1",
      "position": 0
    },
    {
      "url": "hp-pavilion-15-eg2034tx-i7-6k780pa-ab.jpg",
      "alt": "Mô tả hình ảnh 2",
      "caption": "Chú thích hình ảnh 2",
      "position": 1
    }
  ],
  "stock": 10,
  "discount": 10
}


###
DELETE   http://localhost:8080/api/v1/products/6570a1c2cc785a37486a3e49 HTTP/1.1


###
PATCH  http://localhost:9494/api/v1/products/2 HTTP/1.1
content-type: application/json

{
    "description": "dây điện: 3.7m,Công suất hút: 12000 Pa"
}