#Get all User

GET  http://localhost:9494/api/v1/suppliers HTTP/1.1

###

#Post a new user
POST http://localhost:8080/api/v1/suppliers HTTP/1.1
content-type: application/json

{
    "name": "JBL Audio",
    "email": "jbl@audio.com",
    "phoneNumber": "678-901-2345",
    "address": "Los Angeles, CA, USA"

}

###
DELETE   http://localhost:9494/api/v1/suppliers/1 HTTP/1.1


###
PATCH  http://localhost:9494/api/v1/suppliers/1 HTTP/1.1
content-type: application/json

{
    "email": "hxtrong@gmail.com"
}